### PR TITLE
fix(build): upload full bundle directory archive to GitHub releases

### LINKED ISSUE #23770: gemini.js single file 0.35.0 no longer runnable
### What happened?

I used to run gemini-cli by downloading the latest gemini.js, which no longer works with 0.35:

```
node ~/Downloads/gemini.js 
node:internal/modules/esm/resolve:274
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/space/dmueller/Downloads/chunk-WMKFGSOV.js' imported from /space/dmueller/Downloads/gemini.js
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:864:10)
    at defaultResolve (node:internal/modules/esm/resolve:990:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:718:20)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:735:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:764:52)
    at #resolve (node:internal/modules/esm/loader:700:17)
    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:620:35)
    at ModuleJob.syncLink (node:internal/modules/esm/module_job:143:33)
    at ModuleJob.link (node:internal/modules/esm/module_job:228:17) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///my/home/dir/Downloads/chunk-WMKFGSOV.js'
}

```

### What did you expect to happen?

gemini to work properly

### Client information

<details>
<summary>Client Information</summary>

0.35.0 from https://github.com/google-gemini/gemini-cli/releases/download/v0.35.0/gemini.js

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by sehoon38**
## Summary

This PR fixes issue #23770 where the standalone `gemini.js` artifact uploaded to GitHub releases was failing to run due to missing external chunk files.

Instead of disabling code splitting (which would break the startup performance improvements introduced in #22117 and cause an ESM loader deadlock during single-file bundling), this PR updates the release workflow to compress the entire `bundle/` directory into `gemini-cli-bundle.zip` and attach that archive to the release.

## Details

When `splitting: true` is enabled in esbuild, the bundle relies on dynamically imported chunks (e.g., `chunk-XXXX.js`). The previous GitHub Action only uploaded the entry point (`bundle/gemini.js`), which resulted in
`ERR_MODULE_NOT_FOUND` errors when users tried to run it standalone. Uploading the full directory archive ensures all chunks are available.

## Related Issues

Fixes #23770

## How to Validate

1. Trigger a release build or run the GitHub Action manually (or mock it locally
   by running `zip -r gemini-cli-bundle.zip bundle/` after `npm run bundle`).
2. Verify that `gemini-cli-bundle.zip` contains both `gemini.js` and all
   associated `chunk-*.js` files.
3. Unzip the archive and run `node gemini.js --version`. It should execute
   successfully.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: .github/actions/publish-release/action.yml [hunk 1]
```diff
@@ -291,8 +291,9 @@ runs:
         INPUTS_PREVIOUS_TAG: '${{ inputs.previous-tag }}'
       shell: 'bash'
       run: |
+        zip -r gemini-cli-bundle.zip bundle/
         gh release create "${INPUTS_RELEASE_TAG}" \
-          bundle/gemini.js \
+          gemini-cli-bundle.zip \
```
Comment (myaaaaaaaaa) [inline .github/actions/publish-release/action.yml:312]: Can you add a step after this that tests the released file to make sure it's working? That way, we can avoid this kind of regression in the future. Thanks!

It should be enough to simply download and unpack the `.zip` release, run `./gemini.js --version`, and check that the version string is correct.

Alternatively, if you're feeling adventurous, try capturing the output of the command below and testing that it contains the string "Google" (although this may be more involved in terms of juggling API keys. [An example of API key usage here](https://github.com/google-gemini/gemini-cli/blob/6e79ea589aaeeeea48e198ed6b4c8fdd4e765595/.github/workflows/eval.yml#L30)):
```sh
./gemini.js --model 'gemini-3-flash-lite' -p 'Explain Gemini AI in few words. Who developed it?'
```

Comment (sehoon38) [reply .github/actions/publish-release/action.yml:312]: makes sense, I added the check! we are also looking into adding a binary (or binaries for multiple platforms), hope that all helps soon.

**Review by abhipatel12 — APPROVED** [review]
