### ISSUE TITLE
Doesn't work with latest stable node v22.17.0

### ISSUE THREAD

**Issue by andzejsw** [google-gemini/gemini-cli#3297]
### What happened?

While package info states that it is working with node versions 18+, it doesn't work with node versions 20+. Documentation should be changed or fixes should be made , so it works with latest stable. Error showing currently: ` error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments`

### What did you expect to happen?

Gemini cli should work with latest node, since it is stated it works with node versiosn 18+

### Client information

<details>

```console
$ gemini /about
# paste output here
```

</details>

### Anything else we need to know?

Issue happened during install process.

**Comment by dtometzki** [comment]
Hi, 

could you briefly explain how you encountered the error?

What steps you do ?

**Comment by andzejsw** [comment]
Hi! First I tried to install gemini-cli under 20x node version, which I had on my Windows 11 PC. It was leading to errors. After that with help of Gemini i learned that i was missing some Visual Studio build tools and I installed all, which was required. It still wasn't working. After that I decided to upgrade my node via downloaded installer to latest stable and checked node version in powershell, which was showing correct version. Then again i tried to instal gemini-cli with terminal command: `npm install -g @google/gemini-cli
gemini` and it still failed. All suggestions I had in browser Gemini version was to downgrade the node version, which I know is wrong, since cli instructions state it should work on node 18+ (PS: Now it shows 20+, which also is os ok for current stable)

**Comment by swissspidy** [comment]
Sorry to hear you're running into these issues.

The error message indicates that you are running into some sort of issue within Node.js / V8 itself, not the Gemini CLI.

> Then again i tried to instal gemini-cli with terminal command: `npm install -g @google/gemini-cli gemini` and it still failed.

Note that `gemini` is something else entirely. You will want only `npm install -g @google/gemini-cli`. So please try that.

You can also try `npx --yes @google/gemini-cli` for a quick start. Does that work for you? If not, please share the full error message/stack.

**Comment by andzejsw** [comment]
Runing `npm install -g @google/gemini-cli` with force i tried multiple times and it didn't work. Will try though npx option.

**Comment by andzejsw** [comment]
Oh. Now global install worked. I guess issue is now solved.
