### ISSUE TITLE
gemini.js single file 0.35.0 no longer runnable

### ISSUE THREAD

**Issue by dirkmueller** [google-gemini/gemini-cli#23770]
### What happened?

I used to run gemini-cli by downloading the latest gemini.js, which no longer works with 0.35:

```
node ~/Downloads/gemini.js 
node:internal/modules/esm/resolve:274
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/space/dmueller/Downloads/chunk-WMKFGSOV.js' imported from /space/dmueller/Downloads/gemini.js
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:864:10)
    at defaultResolve (node:internal/modules/esm/resolve:990:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:718:20)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:735:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:764:52)
    at #resolve (node:internal/modules/esm/loader:700:17)
    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:620:35)
    at ModuleJob.syncLink (node:internal/modules/esm/module_job:143:33)
    at ModuleJob.link (node:internal/modules/esm/module_job:228:17) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///my/home/dir/Downloads/chunk-WMKFGSOV.js'
}

```

### What did you expect to happen?

gemini to work properly

### Client information

<details>
<summary>Client Information</summary>

0.35.0 from https://github.com/google-gemini/gemini-cli/releases/download/v0.35.0/gemini.js

</details>

**Comment by myaaaaaaaaa** [comment]
* gemini.js releases are now part of a zip file as of https://github.com/google-gemini/gemini-cli/releases/tag/v0.36.0-preview.8

**Comment by sehoon38** [comment]
yes, that's how it is for now, we are looking into adding a single binary for each platform.

**Comment by iki** [comment]
@sehoon38 `bun build gemini.js --compile` works for me with extracted [`gemini-cli-bundle.zip`](https://github.com/google-gemini/gemini-cli/releases/latest/download/gemini-cli-bundle.zip)

Also, users can install/update gemini using [mise-en-place](https://mise.jdx.dev):

```toml 
`"github:google-gemini/gemini-cli" = { version = "latest", postinstall = "sh -c -o errexit 'cd $MISE_TOOL_INSTALL_PATH; bun build gemini.js --compile'" }
```
