### PR TITLE
fix(core): skip merged function-response turns when finding the active loop

### PR DESCRIPTION
**Pull request by adamfweidman**
## Summary

Tool calls can be sent to the API without a thought signature, which the API
rejects with `400 INVALID_ARGUMENT`. The bad turn stays in history, so once it
happens the session cannot recover. Skill activation triggers it on every use,
because that call is generated client-side and carries no signature of its own.

Regression from #28407, first shipped in `v0.52.0-nightly.20260716`. Not in
`v0.51.0`.

## Details

`ensureActiveLoopHasThoughtSignatures` finds the start of the active loop by
looking for the last `user` turn containing text. Its comment already describes
the correct rule:

```ts
// ...the last user turn with a text message, i.e. that is not a function response.
if (content.role === 'user' && content.parts?.some((part) => part.text)) {
```

The code never checked for a function response. That was equivalent only while a
user turn was either pure text or pure function response.

#28407 added `coalesceConsecutiveRoles`, which merges adjacent same-role turns —
so a function response turn can now be merged with the prompt that follows it.
Starting the loop at such a turn starts it _later_ than the API starts the turn,
so model turns in between are validated by the API but never receive a synthetic
signature.

The fix adds the missing condition, making the code match its comment and the
API's own turn boundary. One condition, one regression test.

## Related Issues

Regression from #28407.

## How to Validate

```bash
npm test -w @google/gemini-cli-core -- src/core/geminiChat.test.ts
```

The new test builds the merged `functionResponse` + text turn and asserts the
preceding call is signed. It fails on `main`
(`expected undefined to be 'skip_thought_signature_validator'`) and passes with
this change.

Manually: send a prompt, let the model reply, then activate a skill with
`/<skill-name>` and send a follow-up. Before this change the follow-up returns
`400`; after it, it succeeds.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [x] Linux
    - [x] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

**Review by DavidAPierce — APPROVED** [review]
LGTM.
