### ISSUE TITLE
Gemini-cli can not start

### ISSUE THREAD

**Issue by rolandash** [google-gemini/gemini-cli#23192]
### What happened?

When start gemini-cli from terminal, it failed with an error message:
`Keychain initialization encountered an error: Cannot find module '../build/Release/keytar.node'
Require stack:
- /opt/homebrew/Cellar/gemini-cli/0.34.0/libexec/lib/node_modules/@google/gemini-cli/node_modules/keytar/lib/keytar.js`

I am on a MacBook M4. Weeks ago I can run gemini-cli 0.30.0 fine. Today I just upgraded my MacOS to Tahoe 26.3, and gemini-cli to 0.34.0. Then I tried to launch gemini-cli and it could not start anymore.

### What did you expect to happen?

gemini-cli should start up normally.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

Macbook M4 with MacOS version Tahoe 26.3, run from Terminal.

**Comment by rolandash** [comment]
I do not think it is duplicated with https://github.com/google-gemini/gemini-cli/issues/12422 as that was happened on a quite ancient version, and it actually can work on recent version 0.30.0. 
It looks more like a regression, that the problem was fixed in previous versions but somehow is re-introduced later. 

I do not know how to remove the status/possible-duplicate label though, seems not possible on my side.

**Comment by scidomino** [comment]
This very much looks like an issue with homebrew and macos.

**Comment by ipaddicting** [comment]
> This very much looks like an issue with homebrew and macos.

Yes, it's 100% repeatable when updating extension:
```
Keychain initialization encountered an error: Cannot find module '../build/Release/keytar.node' Require stack: - /opt/homebrew/Cellar/gemini-cli/0.37.1/libexec/lib/node_modules/@google/gemini-cli/node_modules/keytar/lib/keytar.js 
Using FileKeychain fallback for secure storage. 
Extension integrity store cannot be verified. 
Please delete /Users/nick/.gemini/extension_integrity.json to reset it.
```
And installing extension as well.

**Comment by Farzy** [comment]
Same issue on macOS Intel 15.7.4, running gemini-cli `0.37.1`, installed with Brew. I was running the command `gemini --list-sessions`:

```
Available sessions for this project (2):
  1. REDACTED
  2. REDACTED
Keychain initialization encountered an error: Cannot find module '../build/Release/keytar.node'
Require stack:
- /usr/local/Cellar/gemini-cli/0.37.1/libexec/lib/node_modules/@google/gemini-cli/node_modules/keytar/lib/keytar.js
Using FileKeychain fallback for secure storage.
Loaded cached credentials.
```

**Comment by ehedlund** [comment]
### Root Cause:
The warning message `Cannot find module '../build/Release/keytar.node'` on startup occurs on some macOS systems when  the CLI is installed via Homebrew. This happens because the pre-built Homebrew package is missing the compiled native module required to access the system keychain in certain environments. **However, the CLI automatically falls back to secure, encrypted file storage and remains fully functional.**

### Next Steps: 
To improve the user experience, I will update the CLI's logging to hide this warning when the fallback is successful. A full resolution for the Homebrew package itself would require changes to the official Homebrew repository to ensure native modules are compiled correctly during their build process.

**Comment by stevenzeck** [comment]
I created an issue in Homebrew Core too: https://github.com/Homebrew/homebrew-core/issues/277548.
