### ISSUE TITLE
test(cli): fix skipped test for cleanupExpiredSessions error handling in gemini.test.tsx

### ISSUE THREAD

**Issue by AdamyaSingh7** [google-gemini/gemini-cli#20704]
### What happened?

The test `should log error when cleanupExpiredSessions fails` in `packages/cli/src/gemini.test.tsx` has been skipped since it was introduced in commit e6344a8c2. 

When unskipped, the test fails with:
TypeError: vi.mocked(...).mockRejectedValue is not a function

This occurs at line 754 because `cleanupExpiredSessions` is imported dynamically inside the test body using `await import()`, but is not properly set up as a vi mock at the module level. As a result, `vi.mocked()` returns the real function which lacks `mockRejectedValue`.

### What did you expect to happen?

The test should pass. The underlying source code in gemini.tsx already handles the error correctly:

try {
  await cleanupExpiredSessions(config, settings.merged);
} catch (e) {
  debugLogger.error('Failed to cleanup expired sessions:', e);
}

The fix requires properly mocking `cleanupExpiredSessions` at the module level, consistent with how other functions are mocked in the same test file.

### Client information

N/A -this is a test infrastructure bug, not a runtime bug.

**Comment by Adib234** [comment]
Thank you for bringing this to our attention. Right now, our engineering team is focusing all resources on critical system maintenance and core stability. Because of this, we don't have immediate plans to address this specific issue, but we truly appreciate you flagging it for us.
