### PR TITLE
fix(cli): generate and attach standalone bundle to GitHub releases

### LINKED ISSUE #23770: gemini.js single file 0.35.0 no longer runnable
### What happened?

I used to run gemini-cli by downloading the latest gemini.js, which no longer works with 0.35:

```
node ~/Downloads/gemini.js 
node:internal/modules/esm/resolve:274
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/space/dmueller/Downloads/chunk-WMKFGSOV.js' imported from /space/dmueller/Downloads/gemini.js
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:864:10)
    at defaultResolve (node:internal/modules/esm/resolve:990:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:718:20)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:735:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:764:52)
    at #resolve (node:internal/modules/esm/loader:700:17)
    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:620:35)
    at ModuleJob.syncLink (node:internal/modules/esm/module_job:143:33)
    at ModuleJob.link (node:internal/modules/esm/module_job:228:17) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///my/home/dir/Downloads/chunk-WMKFGSOV.js'
}

```

### What did you expect to happen?

gemini to work properly

### Client information

<details>
<summary>Client Information</summary>

0.35.0 from https://github.com/google-gemini/gemini-cli/releases/download/v0.35.0/gemini.js

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by sehoon38**
Fixes #23770. Restores `splitting: true` to the main CLI bundle to preserve boot-up time improvements, and adds a separate `cliStandaloneConfig` target in `esbuild.config.js` to generate a fully self-contained standalone executable at `dist/gemini.js`. The `publish-release` GitHub Action has been updated to attach this standalone bundle to GitHub releases instead of the split version.

### CODE REVIEW

File: .github/actions/publish-release/action.yml
Comment (myaaaaaaaaa) [inline .github/actions/publish-release/action.yml:301]: Can you add a step here (between "Create GitHub Release" and "Clean up release branch") that tests the released file to make sure it's working? That way, we can avoid this kind of regression in the future. Thanks!

It should be enough to simply download the release from the previous step, run `./gemini.js --version`, and make sure the version string matches.

Alternatively, if you're feeling adventurous, try capturing the output of this command and testing that it contains the string "Google" (although this may be more involved in terms of juggling API keys. [An example of API key usage here](https://github.com/google-gemini/gemini-cli/blob/6e79ea589aaeeeea48e198ed6b4c8fdd4e765595/.github/workflows/eval.yml#L30)):
```sh
./gemini.js --model 'gemini-3-flash-lite' -p 'Explain Gemini AI in few words. Who developed it?'
```
