### PR TITLE
fix(cli): skip diff hunk markers during @ processing

### LINKED ISSUE #28550: Heap OOM in non-interactive runs: ignore-matcher (path-scurry + minimatch) appears to be rebuilt per file, heap scales with files × .gitignore rules
### Summary

A single non-interactive `--prompt` run (code review over a ~110 KB diff) reliably exhausts the JS heap on a 1,262-file repository. A heap snapshot shows the memory is not the prompt, conversation history, or tool output — it is **file-discovery / ignore-matching machinery**: 354,708 `_PathPosix` (path-scurry) and 210,194 `_Pattern` (minimatch) objects for **1,262 files**, i.e. ~281 path objects and ~167 compiled ignore patterns *per file*.

The repository has ~68 non-comment `.gitignore` rules across 3 files. minimatch expands each rule into ~2.5 patterns, which is almost exactly the 167 patterns-per-file observed (210,194 / 1,262 = 166.6). That is consistent with the ignore matcher being constructed **per file-discovery operation** rather than once and reused.

### Affected versions

* `0.50.0` — reproduced
* `0.52.0` (latest release at time of writing) — reproduced, identical behaviour

### Environment

* macOS, arm64, Node 24
* Also reproduces on `node:lts` (Debian) in GitLab CI, linux/amd64

### Symptoms

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Mark-Compact (reduce) 1645.0 (1672.3) -> 1645.0 (1672.3) MB
  (average mu = 0.977, current mu = 0.001) last resort; GC in old space requested
```

`current mu → 0.001` — the process spends essentially all its time in GC making no forward progress. With a larger heap ceiling it does not recover, it just thrashes for longer: in CI, runs that did not quite tip over instead consumed the full 1 hour job timeout producing no output at all. (Because `--output-format text` buffers until completion, a wedged run emits nothing after the startup banner, which makes this very hard to diagnose from logs.)

### Reproduction

1. Check out a repository with a moderate file count and a non-trivial set of `.gitignore` rules (here: 1,262 tracked files, ~68 ignore rules across 3 `.gitignore` files, a JS/TS monorepo).
2. Use a user `settings.json` with:
   ```json
   {
     "mcpServers": {},
     "tools": { "exclude": ["write_file", "replace", "run_shell_command", "web_fetch", "google_web_search"] },
     "security": { "folderTrust": { "enabled": false } },
     "advanced": { "autoConfigureMemory": false }
   }
   ```
   `advanced.autoConfigureMemory: false` is required so an externally supplied heap ceiling is not overridden.
3. Cap the heap and dump a snapshot on approach:
   ```
   NODE_OPTIONS="--max-old-space-size=1800 --heapsnapshot-near-heap-limit=1"
   ```
4. Run headless, with a ~110 KB prompt (a unified diff) on stdin:
   ```
   gemini --model <model> --approval-mode yolo --skip-trust \
          --output-format text --prompt "Review the diff above." < prompt.md
   ```

OOMs in ~150 s, no output.

### Heap snapshot analysis

Total `self_size` 1,825 MB across 4,271,585 nodes. Top consumers by aggregate `self_size`:

| MB | name | nodes |
|-----|------|-------|
| 446 | `system / TrustedByteArray` | 80,656 |
| 275 | *(unnamed)* | 123,358 |
| 125 | `_PathPosix` | **354,708** |
| 53 | `system / JSArrayBufferData` | 260 |
| 32 | *(CLI bundle source)* | 1 |
| 32 | `(object elements)` | 308,168 |
| 23 | `_Pattern` | **210,194** |
| 21 | `Array` | 668,987 |

By node type: `string` 772 MB (42%), `hidden` 464 MB (25%), `code` 281 MB (15%), `object` 175 MB (10%).

### What this is *not*

Each of these was checked and excluded:

* **Conversation/history accumulation** — the prompt appears in the heap **exactly once**.
* **Prompt / diff size** — the diff text does not appear among the top consumers. A *larger* (169 KB, 34-file) diff on a different repository with fewer ignore rules completes normally in ~240 s.
* **The grep tool** — object counts are byte-identical whether ripgrep is active or the JS `GrepTool` fallback is used (354,708 / 210,194 in both). So this is the file-discovery/ignore layer, not grep.
* **MCP** — reproduced with `mcpServers: {}`.
* **`read_many_files` / `invoke_agent`** — reproduced with both denied.
* **Heap ceiling** — the CLI had already granted itself ~7.9 GB via `autoConfigureMemory` (50% of RAM) in CI and still died at ~1.9 GB, i.e. it exhausts available memory rather than a V8 limit.

### Scaling across repositories

`files × ignore-rules` ranks the observed behaviour cleanly (same tool, same prompt shape, same model):

| repo | files | ignore rules | product | result |
|------|-------|--------------|---------|--------|
| A | 350 | 10 | 3,500 | ok (~60–140 s) |
| B | 508 | 48 | 24,384 | ok (~100–290 s) |
| C | 1,118 | 31 | 34,658 | ok (~240 s) |
| D | 1,260 | 68 | **85,680** | **OOM** |

Within repo D, a smaller change set (19 changed files) completes while a larger one (29 changed files) OOMs, so the product looks like a baseline cost that the run's own workload then multiplies.

### Suggested area

`FileDiscoveryService` / the gitignore filtering path: construct and cache the minimatch pattern set and path-scurry walker once per session (or per root) instead of per file/operation. Note [#26657](https://github.com/google-gemini/gemini-cli/pull/26657) previously addressed a related enumeration OOM via streaming `fs.opendir`; this appears to be a distinct allocation path.

### Possibly related open issues

These report high memory / OOM without diagnostics and may share this root cause: #27938, #27976, #28357, #28537.

### PR DESCRIPTION
**Pull request by tlysanhuo**
## Summary

Prevent unified and combined diff hunk markers from being interpreted as `@file` references. This removes two recursive workspace-wide glob searches per hunk, preventing `minimatch`/`path-scurry` heap growth on large diff prompts.

## Details

- Reject only bare runs of `@` bounded by ASCII whitespace or end of input.
- Preserve the prompt byte-for-byte when it contains `@@ ... @@` or `@@@ ... @@@` markers.
- Preserve real paths beginning with `@`, such as `@@scope.ts`.
- A two-hunk regression case made four glob calls before this change and zero after it.

## Related Issues

Fixes #28550

## How to Validate

- `npm test -w @google/gemini-cli -- src/ui/hooks/atCommandProcessor.test.ts src/ui/utils/commandUtils.test.ts` — 101 tests passed.
- Preflight format, lint, build, typecheck, CLI, core, and SDK suites passed. The VS Code companion suite also passed separately: 40 passed, 1 skipped.
- `npm run test:memory` — 6/7 scenarios passed; the remaining unrelated baseline is already unstable on this exact upstream SHA, whose Nightly job is red: https://github.com/google-gemini/gemini-cli/actions/runs/30418799040
- `npm run test:perf` — blocked before collection by the existing `canUseRipgrep is not a function` fixture regression, reproduced identically by the upstream Nightly job on this SHA: https://github.com/google-gemini/gemini-cli/actions/runs/30421363714

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (not needed; internal parser fix)
- [x] Added/updated tests
- [x] Noted breaking changes (none)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

**Comment by tlysanhuo** [comment]
Rebased onto current `main` (`dc859e8`); current head is `23970dd`, with no overlap or conflict in the updated upstream files. Local verification on this head: the two affected suites pass 101/101 tests, and full-repository `typecheck` and `lint` pass. The Google CLA, size label, and GitHub Actions scan are green. The fork-gated `Testing: CI`, `Trigger E2E`, and `Links` workflows are awaiting maintainer approval, and the change is ready for human review.

**Comment by tlysanhuo** [comment]
Rebased onto current main 2139b121b; current head is edb79e222. The affected upstream files had no intervening changes. The two regression suites pass 101/101, repository lint and typecheck pass, and the CLA plus current GitHub checks are green. I also updated #28550 with current-version reproduction evidence and a request for the help wanted designation. This is ready for human review.

**Comment by tlysanhuo** [comment]
@google-gemini/gemini-cli-maintainers Could someone review this before the PR-nudge window expires? Current head `edb79e2` is conflict-free; CLA, size, and scan checks pass. `Testing: CI`, `Trigger E2E`, and `Links` remain `action_required` pending maintainer approval. Issue #28550 now contains a current-main reproduction, but still has `status/need-information` and no `help wanted` label. Could a maintainer review that evidence, update eligibility if appropriate, and approve the gated workflows? The bot notice indicates the PR may close around August 13.
